'use client';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { createClient } from '@/lib/supabase';
import { Video, Image as ImageIcon, FileText, Mic2, Globe2, Sparkles, LogOut, FolderOpen, BarChart3, BrainCircuit, Settings2 } from 'lucide-react';
import { useLanguage } from '@/lib/i18n';
import { LanguageToggle } from '@/components/language-toggle';
import { WorkspaceSwitcher } from '@/components/workspace-switcher';

export default function DashboardPage(){
  const router=useRouter(); const supabase=createClient(); const {t}=useLanguage();
  const [brand,setBrand]=useState<any>(null); const [wallet,setWallet]=useState(0); const [prompt,setPrompt]=useState(''); const [loading,setLoading]=useState(true);
  useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/auth');return;}const {data:activeOrg}=await supabase.rpc('get_active_organization');const membership=activeOrg?{organization_id:String(activeOrg)}:null;if(!membership){router.replace('/onboarding');return;}const [{data:b},{data:w}]=await Promise.all([supabase.from('brands').select('*').eq('organization_id',membership.organization_id).order('created_at',{ascending:true}).limit(1).maybeSingle(),supabase.from('credit_wallets').select('balance').eq('organization_id',membership.organization_id).single()]);if(!b){router.replace('/onboarding');return;}setBrand(b);setWallet(w?.balance??0);setLoading(false);})()},[]);
  const actions=[[Video,t('videoAd'),t('dashboardVideoDesc')],[ImageIcon,t('socialDesign'),t('dashboardSocialDesc')],[FileText,t('adCopy'),t('dashboardCopyDesc')],[Mic2,t('voiceOver'),t('dashboardVoiceDesc')],[Globe2,t('landingPage'),t('dashboardLandingDesc')]];
  function run(){if(!prompt.trim())return;sessionStorage.setItem('creative-prompt',prompt.trim());router.push('/creative');}
  if(loading)return <main className="p-10 text-center text-zinc-400">{t('loading')}</main>;
  return <main className="min-h-screen px-5 py-6"><div className="mx-auto max-w-7xl"><header className="flex items-center justify-between gap-4"><div><div className="flex items-center gap-2 text-xl font-black"><Sparkles size={20}/> AI Creative OS</div><div className="mt-1 text-sm text-zinc-500">{brand?.name}</div></div><div className="flex items-center gap-2"><button className="btn btn-ghost inline-flex items-center gap-2" onClick={()=>router.push('/brand')}><BrainCircuit size={17}/><span className="hidden sm:inline">{t('brandBrain')}</span></button><button className="btn btn-ghost inline-flex items-center gap-2" onClick={()=>router.push('/projects')}><FolderOpen size={17}/><span className="hidden sm:inline">{t('projectsTitle')}</span></button><button className="btn btn-ghost inline-flex items-center gap-2" onClick={()=>router.push('/usage')}><BarChart3 size={17}/><span className="hidden sm:inline">{t('usageTitle')}</span></button><button className="btn btn-ghost inline-flex items-center gap-2" onClick={()=>router.push('/settings')}><Settings2 size={17}/><span className="hidden sm:inline">{t('settingsTitle')}</span></button><WorkspaceSwitcher/><LanguageToggle/><div className="rounded-xl border border-zinc-800 bg-zinc-900 px-4 py-2 text-sm">{wallet} {t('credits')}</div><button className="btn btn-ghost" onClick={async()=>{await supabase.auth.signOut();router.push('/auth')}}><LogOut size={17}/></button></div></header><section className="mx-auto mt-20 max-w-4xl text-center"><h1 className="text-4xl font-black md:text-6xl">{t('whatCreate')}</h1><p className="mt-4 text-zinc-500">{t('plannerHint')}</p><div className="card mt-8 p-3"><textarea className="min-h-36 w-full resize-none bg-transparent p-4 text-lg outline-none" value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder={t('promptPlaceholder')}/><div className="flex justify-end"><button className="btn btn-primary" onClick={run} disabled={!prompt.trim()}>{t('startExecution')}</button></div></div></section><section className="mt-12 grid gap-4 md:grid-cols-5">{actions.map(([Icon,title,desc])=>{const I=Icon as typeof Video;return <button key={String(title)} onClick={()=>{setPrompt(String(title));window.scrollTo({top:0,behavior:'smooth'})}} className="card p-5 text-start transition hover:-translate-y-1 hover:border-violet-500/40"><I className="mb-5 text-violet-300"/><div className="font-bold">{String(title)}</div><div className="mt-2 text-sm leading-6 text-zinc-500">{String(desc)}</div></button>})}</section></div></main>;
}
