'use client';
import { FormEvent, useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { createClient } from '@/lib/supabase';
import { useLanguage } from '@/lib/i18n';
import { LanguageToggle } from '@/components/language-toggle';

export default function OnboardingPage(){
  const router=useRouter(); const supabase=createClient(); const {t,locale}=useLanguage();
  const [orgId,setOrgId]=useState(''); const [name,setName]=useState(''); const [industry,setIndustry]=useState(''); const [description,setDescription]=useState(''); const [tone,setTone]=useState(''); const [busy,setBusy]=useState(true); const [error,setError]=useState('');
  useEffect(()=>{if(!tone)setTone(t('defaultTone'));},[t,tone]);
  useEffect(()=>{(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/auth');return;}const {data,error}=await supabase.rpc('get_active_organization');if(error||!data){setError(error?.message||'No workspace');setBusy(false);return;}setOrgId(String(data));setBusy(false);})()},[]);
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');const {data:{user}}=await supabase.auth.getUser();if(!user||!orgId){setError(t('authWorkspaceError'));setBusy(false);return;}const {error:brandError}=await supabase.from('brands').insert({organization_id:orgId,created_by:user.id,name,industry,description,tone_of_voice:{primary:tone},defaults:{language:locale,market:'EG'}});if(brandError){setError(brandError.message);setBusy(false);return;}const {error:profileError}=await supabase.from('profiles').update({onboarding_completed:true,locale}).eq('user_id',user.id);if(profileError){setError(profileError.message);setBusy(false);return;}router.push('/dashboard');}
  if(busy&&!orgId)return <main className="p-10 text-center text-zinc-400">{t('loadingWorkspace')}</main>;
  return <main className="min-h-screen px-6 py-14"><div className="mx-auto max-w-2xl"><div className="mb-5 flex justify-end"><LanguageToggle/></div><div className="mb-8"><div className="text-sm text-violet-300">{t('onboardingStep')}</div><h1 className="mt-2 text-4xl font-black">{t('tellBrand')}</h1><p className="mt-3 text-zinc-500">{t('brandHelp')}</p></div><form onSubmit={submit} className="card space-y-5 p-7"><div><label className="mb-2 block text-sm text-zinc-400">{t('brandName')}</label><input className="input" value={name} onChange={e=>setName(e.target.value)} placeholder={t('brandPlaceholder')} required/></div><div><label className="mb-2 block text-sm text-zinc-400">{t('industry')}</label><input className="input" value={industry} onChange={e=>setIndustry(e.target.value)} placeholder={t('industryPlaceholder')} required/></div><div><label className="mb-2 block text-sm text-zinc-400">{t('businessDescription')}</label><textarea className="input min-h-28" value={description} onChange={e=>setDescription(e.target.value)} placeholder={t('businessPlaceholder')}/></div><div><label className="mb-2 block text-sm text-zinc-400">{t('brandTone')}</label><input className="input" value={tone} onChange={e=>setTone(e.target.value)}/></div>{error&&<div className="rounded-xl border border-red-900/50 bg-red-950/30 p-3 text-sm text-red-300">{error}</div>}<button className="btn btn-primary w-full" disabled={busy}>{busy?t('saving'):t('saveEnter')}</button></form></div></main>;
}
