'use client';
import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { createClient } from '@/lib/supabase';
import { getActiveOrganizationId } from '@/lib/active-org';
import { useLanguage } from '@/lib/i18n';
import { LanguageToggle } from '@/components/language-toggle';
import { WorkspaceSwitcher } from '@/components/workspace-switcher';
import { ArrowLeft, Bot, CheckCircle2, CircleAlert, CreditCard, RefreshCw, Settings2, Shield, Users } from 'lucide-react';

type Member={user_id:string;role:string;created_at:string}; type Invite={id:string;email:string;role:string;status:string;expires_at:string}; type ProviderSetting={id?:string;kind:string;quality_tier:string;provider_code:string;model_code:string;env_prefix:string;priority:number;enabled:boolean;is_fallback:boolean};
export default function SettingsPage(){
  const supabase=useMemo(()=>createClient(),[]); const {t,locale}=useLanguage();
  const [orgId,setOrgId]=useState(''); const [role,setRole]=useState('viewer'); const [members,setMembers]=useState<Member[]>([]); const [invites,setInvites]=useState<Invite[]>([]); const [email,setEmail]=useState(''); const [inviteRole,setInviteRole]=useState('editor'); const [inviteUrl,setInviteUrl]=useState(''); const [message,setMessage]=useState('');
  const [policy,setPolicy]=useState<any>(null); const [providers,setProviders]=useState<ProviderSetting[]>([]); const [subscription,setSubscription]=useState<any>(null); const [plan,setPlan]=useState<any>(null); const [readiness,setReadiness]=useState<any>(null); const [loading,setLoading]=useState(true);
  async function token(){const {data:{session}}=await supabase.auth.getSession();return session?.access_token||''}
  async function load(){setLoading(true);try{const {data:{user}}=await supabase.auth.getUser();if(!user)return;const oid=await getActiveOrganizationId(supabase);setOrgId(oid);const [{data:me},{data:ms},{data:is},{data:p},{data:ps},{data:sub}]=await Promise.all([supabase.from('organization_members').select('role').eq('organization_id',oid).eq('user_id',user.id).single(),supabase.from('organization_members').select('user_id,role,created_at').eq('organization_id',oid).order('created_at'),supabase.from('team_invitations').select('id,email,role,status,expires_at').eq('organization_id',oid).order('created_at',{ascending:false}),supabase.from('organization_ai_policies').select('*').eq('organization_id',oid).single(),supabase.from('organization_provider_settings').select('*').eq('organization_id',oid).order('kind').order('quality_tier'),supabase.from('organization_subscriptions').select('*').eq('organization_id',oid).single()]);setRole(me?.role||'viewer');setMembers((ms||[]) as Member[]);setInvites((is||[]) as Invite[]);setPolicy(p);setProviders((ps||[]) as ProviderSetting[]);setSubscription(sub);if(sub?.plan_key){const {data:bp}=await supabase.from('billing_plans').select('*').eq('plan_key',sub.plan_key).single();setPlan(bp)}const tok=await token();if(tok){const rr=await fetch('/api/admin/readiness',{headers:{Authorization:`Bearer ${tok}`}});if(rr.ok)setReadiness(await rr.json());}}finally{setLoading(false)}}
  useEffect(()=>{load()},[]);
  async function invite(){setMessage('');setInviteUrl('');const tok=await token();const r=await fetch('/api/admin/invitations',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${tok}`},body:JSON.stringify({email,role:inviteRole})});const j=await r.json();if(!r.ok){setMessage(j.error||t('genericError'));return;}setInviteUrl(j.inviteUrl);setEmail('');await load()}
  async function revoke(id:string){const tok=await token();await fetch(`/api/admin/invitations/${id}`,{method:'DELETE',headers:{Authorization:`Bearer ${tok}`}});await load()}
  async function changeMember(userId:string,nextRole:string){const tok=await token();const r=await fetch(`/api/admin/members/${userId}`,{method:'PATCH',headers:{'Content-Type':'application/json',Authorization:`Bearer ${tok}`},body:JSON.stringify({role:nextRole})});if(!r.ok){const j=await r.json();setMessage(j.error||t('genericError'))}await load()}
  async function removeMember(userId:string){const tok=await token();await fetch(`/api/admin/members/${userId}`,{method:'DELETE',headers:{Authorization:`Bearer ${tok}`}});await load()}
  async function savePolicy(){if(!policy)return;const {error}=await supabase.from('organization_ai_policies').update({max_provider_cost_per_generation_usd:Number(policy.max_provider_cost_per_generation_usd),max_provider_cost_per_day_usd:Number(policy.max_provider_cost_per_day_usd),max_credits_per_day:Number(policy.max_credits_per_day),max_retries_per_provider:Number(policy.max_retries_per_provider),max_failovers:Number(policy.max_failovers),request_timeout_ms:Number(policy.request_timeout_ms),moderation_mode:policy.moderation_mode,updated_at:new Date().toISOString()}).eq('organization_id',orgId);setMessage(error?error.message:t('settingsSaved'))}
  async function upsertProvider(row:ProviderSetting){const payload={...row,organization_id:orgId,priority:Number(row.priority),updated_at:new Date().toISOString()};delete (payload as any).id;const {error}=await supabase.from('organization_provider_settings').upsert(payload,{onConflict:'organization_id,kind,quality_tier,provider_code,model_code'});setMessage(error?error.message:t('settingsSaved'));await load()}
  function addProvider(){setProviders(x=>[...x,{kind:'text',quality_tier:'quality',provider_code:'custom',model_code:'model',env_prefix:'TEXT_QUALITY_PRIMARY',priority:100,enabled:false,is_fallback:false}])}
  async function testProvider(row:ProviderSetting){const tok=await token();if(!tok)return;setMessage('');const r=await fetch('/api/admin/providers/test',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${tok}`},body:JSON.stringify({kind:row.kind,quality:row.quality_tier})});const data=await r.json().catch(()=>({}));setMessage(r.ok?`${t('providerTestSuccess')} · ${data.provider||row.provider_code} · ${data.latencyMs??'?'}ms`:`${t('providerTestFailed')}: ${data.error||r.status}`)}
  const canAdmin=role==='owner'||role==='admin';
  if(loading)return <main className="p-10 text-center text-zinc-400">{t('loading')}</main>;
  return <main className="min-h-screen px-5 py-7"><div className="mx-auto max-w-6xl"><header className="flex flex-wrap items-center justify-between gap-3"><Link href="/dashboard" className="btn btn-ghost inline-flex items-center gap-2"><ArrowLeft size={16}/>{t('backDashboard')}</Link><div className="flex items-center gap-2"><WorkspaceSwitcher/><LanguageToggle/></div></header><section className="mt-10"><div className="flex items-center gap-3"><Settings2 className="text-violet-300"/><div><h1 className="text-4xl font-black">{t('settingsTitle')}</h1><p className="mt-1 text-zinc-500">{t('settingsSubtitle')}</p></div></div>{message&&<div className="mt-5 rounded-xl border border-zinc-800 bg-zinc-900 p-3 text-sm">{message}</div>}

  <div className="mt-8 grid gap-6 lg:grid-cols-2">
    <section className="card p-6"><div className="flex items-center gap-2"><Users className="text-violet-300"/><h2 className="text-xl font-black">{t('teamTitle')}</h2></div><p className="mt-2 text-sm text-zinc-500">{t('teamSubtitle')}</p>{canAdmin&&<div className="mt-5 grid gap-3 sm:grid-cols-[1fr_140px_auto]"><input className="input" type="email" placeholder={t('email')} value={email} onChange={e=>setEmail(e.target.value)}/><select className="input" value={inviteRole} onChange={e=>setInviteRole(e.target.value)}><option value="admin">Admin</option><option value="editor">Editor</option><option value="viewer">Viewer</option></select><button className="btn btn-primary" onClick={invite} disabled={!email}>{t('sendInvite')}</button></div>}{inviteUrl&&<div className="mt-3 rounded-xl border border-emerald-900/50 bg-emerald-950/20 p-3 text-sm"><div className="font-bold">{t('inviteLink')}</div><div className="mt-1 break-all text-emerald-300">{inviteUrl}</div></div>}<div className="mt-5 space-y-2">{members.map(m=><div key={m.user_id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-zinc-800 p-3"><div><div className="font-mono text-xs text-zinc-400">{m.user_id.slice(0,12)}…</div><div className="text-sm font-bold">{m.role}</div></div>{canAdmin&&m.role!=='owner'&&<div className="flex items-center gap-2"><select className="input py-2" value={m.role} onChange={e=>changeMember(m.user_id,e.target.value)}><option value="admin">Admin</option><option value="editor">Editor</option><option value="viewer">Viewer</option></select><button className="btn btn-ghost" onClick={()=>removeMember(m.user_id)}>{t('remove')}</button></div>}</div>)}</div>{invites.filter(i=>i.status==='pending').length>0&&<div className="mt-5"><div className="text-sm font-bold">{t('pendingInvites')}</div>{invites.filter(i=>i.status==='pending').map(i=><div key={i.id} className="mt-2 flex items-center justify-between rounded-xl border border-zinc-800 p-3 text-sm"><span>{i.email} · {i.role}</span>{canAdmin&&<button className="text-red-300" onClick={()=>revoke(i.id)}>{t('revoke')}</button>}</div>)}</div>}</section>

    <section className="card p-6"><div className="flex items-center gap-2"><CreditCard className="text-violet-300"/><h2 className="text-xl font-black">{t('billingTitle')}</h2></div><div className="mt-5 rounded-2xl border border-zinc-800 p-5"><div className="text-sm text-zinc-500">{t('currentPlan')}</div><div className="mt-1 text-3xl font-black">{locale==='ar'?plan?.name_ar:plan?.name_en}</div><div className="mt-3 grid grid-cols-2 gap-3 text-sm"><div><span className="text-zinc-500">{t('monthlyCredits')}</span><div className="font-bold">{plan?.monthly_credits??0}</div></div><div><span className="text-zinc-500">{t('includedSeats')}</span><div className="font-bold">{plan?.included_seats??1}</div></div></div><div className="mt-3 text-sm text-zinc-500">{t('subscriptionStatus')}: <span className="text-zinc-200">{subscription?.status||'—'}</span></div></div><div className="mt-4 rounded-xl border border-amber-900/50 bg-amber-950/20 p-3 text-sm text-amber-200">{t('billingNotConnected')}</div></section>

    <section className="card p-6 lg:col-span-2"><div className="flex items-center gap-2"><Shield className="text-violet-300"/><h2 className="text-xl font-black">{t('aiPolicyTitle')}</h2></div><p className="mt-2 text-sm text-zinc-500">{t('aiPolicySubtitle')}</p>{policy&&<div className="mt-5 grid gap-4 md:grid-cols-4"><Field label={t('perGenerationBudget')} value={policy.max_provider_cost_per_generation_usd} onChange={v=>setPolicy({...policy,max_provider_cost_per_generation_usd:v})}/><Field label={t('dailyBudget')} value={policy.max_provider_cost_per_day_usd} onChange={v=>setPolicy({...policy,max_provider_cost_per_day_usd:v})}/><Field label={t('dailyCreditCap')} value={policy.max_credits_per_day} onChange={v=>setPolicy({...policy,max_credits_per_day:v})}/><Field label={t('timeoutMs')} value={policy.request_timeout_ms} onChange={v=>setPolicy({...policy,request_timeout_ms:v})}/><Field label={t('retries')} value={policy.max_retries_per_provider} onChange={v=>setPolicy({...policy,max_retries_per_provider:v})}/><Field label={t('failovers')} value={policy.max_failovers} onChange={v=>setPolicy({...policy,max_failovers:v})}/><label className="block"><span className="text-xs font-bold text-zinc-500">{t('moderationMode')}</span><select className="input mt-2" value={policy.moderation_mode} onChange={e=>setPolicy({...policy,moderation_mode:e.target.value})}><option value="enforce">enforce</option><option value="warn">warn</option><option value="off">off</option></select></label><div className="flex items-end"><button className="btn btn-primary w-full" disabled={!canAdmin} onClick={savePolicy}>{t('saveSettings')}</button></div></div>}</section>

    <section className="card p-6 lg:col-span-2"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2"><Bot className="text-violet-300"/><h2 className="text-xl font-black">{t('providersTitle')}</h2></div>{canAdmin&&<button className="btn btn-ghost" onClick={addProvider}>+ {t('addProvider')}</button>}</div><p className="mt-2 text-sm text-zinc-500">{t('providersSubtitle')}</p><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead className="text-zinc-500"><tr><th className="p-2 text-start">Kind</th><th className="p-2 text-start">Tier</th><th className="p-2 text-start">Provider</th><th className="p-2 text-start">Model</th><th className="p-2 text-start">ENV prefix</th><th className="p-2 text-start">Priority</th><th className="p-2">Enabled</th><th className="p-2"></th></tr></thead><tbody>{providers.map((p,i)=><tr key={p.id||`new-${i}`} className="border-t border-zinc-900"><td className="p-2"><select className="input py-2" value={p.kind} onChange={e=>setProviders(x=>x.map((v,j)=>j===i?{...v,kind:e.target.value}:v))}><option>text</option><option>image</option><option>audio</option><option>video</option></select></td><td className="p-2"><select className="input py-2" value={p.quality_tier} onChange={e=>setProviders(x=>x.map((v,j)=>j===i?{...v,quality_tier:e.target.value}:v))}><option>fast</option><option>quality</option><option>ultra</option></select></td>{['provider_code','model_code','env_prefix'].map(k=><td key={k} className="p-2"><input className="input py-2" value={(p as any)[k]} onChange={e=>setProviders(x=>x.map((v,j)=>j===i?{...v,[k]:e.target.value}:v))}/></td>)}<td className="p-2"><input className="input py-2" type="number" value={p.priority} onChange={e=>setProviders(x=>x.map((v,j)=>j===i?{...v,priority:Number(e.target.value)}:v))}/></td><td className="p-2 text-center"><input type="checkbox" checked={p.enabled} onChange={e=>setProviders(x=>x.map((v,j)=>j===i?{...v,enabled:e.target.checked}:v))}/></td><td className="p-2"><div className="flex gap-2"><button className="btn btn-ghost" disabled={!canAdmin} onClick={()=>upsertProvider(p)}>{t('save')}</button>{p.kind==='text'&&p.enabled&&<button className="btn btn-ghost" disabled={!canAdmin} onClick={()=>testProvider(p)}>{t('testProvider')}</button>}</div></td></tr>)}</tbody></table>{providers.length===0&&<div className="p-6 text-center text-zinc-500">{t('noProviderSettings')}</div>}</div><div className="mt-4 rounded-xl border border-zinc-800 bg-zinc-950 p-3 text-xs text-zinc-400">{t('providerSecretHint')}</div></section>

    <section className="card p-6 lg:col-span-2"><div className="flex items-center gap-2"><RefreshCw className="text-violet-300"/><h2 className="text-xl font-black">{t('readinessTitle')}</h2></div><p className="mt-2 text-sm text-zinc-500">{t('readinessSubtitle')}</p><div className="mt-5 grid gap-3 md:grid-cols-3">{(readiness?.checks||[]).map((c:any)=><div key={c.key} className="flex items-center gap-3 rounded-xl border border-zinc-800 p-4">{c.ok?<CheckCircle2 className="text-emerald-400" size={20}/>:<CircleAlert className="text-amber-400" size={20}/>}<div><div className="font-bold">{c.key.replaceAll('_',' ')}</div><div className="text-xs text-zinc-500">{c.ok?t('configured'):t('notConfigured')}</div></div></div>)}</div>{readiness&&<div className={`mt-4 rounded-xl border p-4 text-sm ${readiness.readyForPrivateBeta?'border-emerald-900/50 bg-emerald-950/20 text-emerald-200':'border-amber-900/50 bg-amber-950/20 text-amber-200'}`}>{readiness.readyForPrivateBeta?t('privateBetaReady'):t('privateBetaNotReady')}</div>}</section>
  </div></section></div></main>;
}
function Field({label,value,onChange}:{label:string;value:any;onChange:(v:string)=>void}){return <label className="block"><span className="text-xs font-bold text-zinc-500">{label}</span><input className="input mt-2" value={value??''} onChange={e=>onChange(e.target.value)}/></label>}
