'use client';
import { useEffect, useMemo, useState } from 'react';
import { createClient } from '@/lib/supabase';
import { useLanguage } from '@/lib/i18n';
import { AppShell } from '@/components/app-shell';
import { ImageIcon, Mic2, Sparkles, Video, WandSparkles, Film, CheckCircle2, Loader2 } from 'lucide-react';

type Brief={objective:string;audience:string;angle:string;offer:string;hooks:string[];concepts:{title:string;idea:string}[];script:string;mode:'provider'|'development'};
type Variant={variantKey:'A'|'B'|'C';title:string;angle:string;hook:string;primaryText:string;headline:string;cta:string;script:string;audience:string;rationale:string};
type Scene={scene:number;durationSeconds:number;shot:string;visualPrompt:string;voiceover:string;onScreenText:string};
type SceneAsset={imageUrl:string;storagePath:string;mode:'provider'|'development';generationId:string};
type VoiceAsset={audioUrl:string;storagePath:string;mode:'provider'|'development';generationId:string};
type VideoAsset={jobId:string;status:'processing'|'succeeded'|'failed';mode:'provider'|'development';videoUrl?:string;storagePath?:string;posterUrl?:string;durationSeconds?:number};
type FinalAsset={jobId?:string;status?:'processing'|'succeeded'|'failed';progress?:number;mode:'provider'|'development';videoUrl?:string;manifestUrl?:string;storagePath?:string};

export default function CreativePage(){
  const supabase=useMemo(()=>createClient(),[]); const {t,locale}=useLanguage();
  const [prompt,setPrompt]=useState(''); const [brief,setBrief]=useState<Brief|null>(null); const [projectId,setProjectId]=useState(''); const [storyboard,setStoryboard]=useState<Scene[]|null>(null);
  const [busy,setBusy]=useState(false); const [storyBusy,setStoryBusy]=useState(false); const [error,setError]=useState(''); const [saved,setSaved]=useState(false);
  const [sceneBusy,setSceneBusy]=useState<Record<number,boolean>>({}); const [assets,setAssets]=useState<Record<number,SceneAsset>>({}); const [allBusy,setAllBusy]=useState(false);
  const [voiceBusy,setVoiceBusy]=useState<Record<number,boolean>>({}); const [voices,setVoices]=useState<Record<number,VoiceAsset>>({});
  const [videoBusy,setVideoBusy]=useState<Record<number,boolean>>({}); const [videos,setVideos]=useState<Record<number,VideoAsset>>({});
  const [variants,setVariants]=useState<Variant[]>([]); const [variantBusy,setVariantBusy]=useState(false); const [selectedVariant,setSelectedVariant]=useState<Variant|null>(null);
  const [assemblyBusy,setAssemblyBusy]=useState(false); const [finalAsset,setFinalAsset]=useState<FinalAsset|null>(null); const [productionBusy,setProductionBusy]=useState(false); const [quality,setQuality]=useState<'fast'|'quality'|'ultra'>('quality');
  useEffect(()=>{setPrompt(sessionStorage.getItem('creative-prompt')??'');},[]);

  function message(error:unknown){const raw=error instanceof Error?error.message:t('genericError');return raw==='insufficient_credits'?t('insufficientCredits'):raw;}
  async function authToken(){const {data:{session}}=await supabase.auth.getSession();if(!session?.access_token)throw new Error('Unauthorized');return session.access_token;}
  async function run(){if(!prompt.trim()){setError(t('emptyPrompt'));return;}setBusy(true);setError('');setSaved(false);try{const token=await authToken();const r=await fetch('/api/creative-brief',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${token}`},body:JSON.stringify({prompt,locale,quality})});const json=await r.json();if(!r.ok)throw new Error(json.error||'Request failed');setBrief(json.brief);setProjectId(json.projectId);setStoryboard(null);setVariants([]);setSelectedVariant(null);setAssets({});setVoices({});setVideos({});setFinalAsset(null);setSaved(true);}catch(e){setError(message(e));}finally{setBusy(false)}}
  async function generateVariants(){if(!brief||!projectId)return;setVariantBusy(true);setError('');try{const token=await authToken();const r=await fetch('/api/campaign-variants',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${token}`},body:JSON.stringify({projectId,brief,locale,quality})});const json=await r.json();if(!r.ok)throw new Error(json.error||'Variant generation failed');setVariants(json.variants??[]);setSelectedVariant((json.variants??[])[0]??null);}catch(e){setError(message(e));}finally{setVariantBusy(false)}}
  async function makeStoryboard(){if(!brief||!projectId)return;setStoryBusy(true);setError('');try{const token=await authToken();const r=await fetch('/api/storyboard',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${token}`},body:JSON.stringify({projectId,brief,variant:selectedVariant,locale,quality})});const json=await r.json();if(!r.ok)throw new Error(json.error||'Request failed');setStoryboard(json.storyboard.scenes);setAssets({});setVoices({});setVideos({});setFinalAsset(null);}catch(e){setError(message(e));}finally{setStoryBusy(false)}}
  async function generateScene(sc:Scene){if(!projectId)return null;setSceneBusy(x=>({...x,[sc.scene]:true}));setError('');try{const token=await authToken();const r=await fetch('/api/generate-image',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${token}`},body:JSON.stringify({projectId,scene:sc.scene,prompt:sc.visualPrompt,locale,quality})});const json=await r.json();if(!r.ok)throw new Error(json.error||'Image generation failed');setAssets(x=>({...x,[sc.scene]:json}));return json as SceneAsset;}catch(e){setError(message(e));return null;}finally{setSceneBusy(x=>({...x,[sc.scene]:false}))}}
  async function generateVoice(sc:Scene){if(!projectId)return null;setVoiceBusy(x=>({...x,[sc.scene]:true}));setError('');try{const token=await authToken();const r=await fetch('/api/generate-voice',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${token}`},body:JSON.stringify({projectId,scene:sc.scene,text:sc.voiceover,locale,durationSeconds:sc.durationSeconds,quality})});const json=await r.json();if(!r.ok)throw new Error(json.error||'Voice generation failed');setVoices(x=>({...x,[sc.scene]:json}));return json as VoiceAsset;}catch(e){setError(message(e));return null;}finally{setVoiceBusy(x=>({...x,[sc.scene]:false}))}}
  async function pollVideo(jobId:string,scene:number,tries=0):Promise<VideoAsset|null>{if(tries>60){setError(t('videoTimeout'));return null;}await new Promise(r=>setTimeout(r,4000));const token=await authToken();const res=await fetch(`/api/video-jobs/${jobId}`,{headers:{Authorization:`Bearer ${token}`}});const json=await res.json();if(!res.ok)throw new Error(json.error||'Video status failed');if(json.status==='processing')return pollVideo(jobId,scene,tries+1);if(json.status==='failed')throw new Error(t('videoFailed'));const asset={...json,status:'succeeded'} as VideoAsset;setVideos(x=>({...x,[scene]:asset}));return asset;}
  async function generateVideo(sc:Scene,image?:SceneAsset){const img=image??assets[sc.scene];if(!projectId||!img)return null;setVideoBusy(x=>({...x,[sc.scene]:true}));setError('');try{const token=await authToken();const r=await fetch('/api/video-jobs',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${token}`},body:JSON.stringify({projectId,scene:sc.scene,prompt:sc.visualPrompt,imageUrl:img.imageUrl,imageStoragePath:img.storagePath,durationSeconds:sc.durationSeconds,locale,quality})});const json=await r.json();if(!r.ok)throw new Error(json.error||'Video generation failed');const initial={...json} as VideoAsset;setVideos(x=>({...x,[sc.scene]:initial}));if(json.status==='processing')return await pollVideo(json.jobId,sc.scene);return initial;}catch(e){setError(message(e));return null;}finally{setVideoBusy(x=>({...x,[sc.scene]:false}))}}
  async function generateAll(){if(!storyboard?.length)return;setAllBusy(true);setError('');try{for(const sc of storyboard){if(!assets[sc.scene])await generateScene(sc);}}finally{setAllBusy(false)}}
  async function produceAll(){if(!storyboard?.length)return;setProductionBusy(true);setError('');try{for(const sc of storyboard){let img=assets[sc.scene];if(!img){const made=await generateScene(sc);if(!made)break;img=made;}if(!voices[sc.scene])await generateVoice(sc);if(!videos[sc.scene])await generateVideo(sc,img);}}finally{setProductionBusy(false)}}
  async function pollAssembly(jobId:string,tries=0):Promise<FinalAsset|null>{if(tries>90){setError(t('videoTimeout'));return null;}await new Promise(r=>setTimeout(r,4000));const token=await authToken();const res=await fetch(`/api/assembly-jobs/${jobId}`,{headers:{Authorization:`Bearer ${token}`}});const json=await res.json();if(!res.ok)throw new Error(json.error||'Assembly status failed');setFinalAsset(json);if(json.status==='processing')return pollAssembly(jobId,tries+1);if(json.status==='failed')throw new Error('Assembly failed');return json as FinalAsset;}
  async function assemble(){if(!storyboard?.length||!projectId)return;setAssemblyBusy(true);setError('');try{const token=await authToken();const scenes=storyboard.map(sc=>({scene:sc.scene,durationSeconds:sc.durationSeconds,onScreenText:sc.onScreenText,image:assets[sc.scene]?{url:assets[sc.scene].imageUrl,storagePath:assets[sc.scene].storagePath}:null,voice:voices[sc.scene]?{url:voices[sc.scene].audioUrl,storagePath:voices[sc.scene].storagePath}:null,video:videos[sc.scene]?{url:videos[sc.scene].videoUrl,storagePath:videos[sc.scene].storagePath,mode:videos[sc.scene].mode,posterUrl:videos[sc.scene].posterUrl}:null}));const r=await fetch('/api/assemble-video',{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${token}`},body:JSON.stringify({projectId,scenes,locale,quality})});const json=await r.json();if(!r.ok)throw new Error(json.error||'Assembly failed');setFinalAsset(json);if(json.status==='processing'&&json.jobId)await pollAssembly(json.jobId);}catch(e){setError(message(e));}finally{setAssemblyBusy(false)}}
  const allProductionReady=!!storyboard?.length&&storyboard.every(sc=>voices[sc.scene]&&videos[sc.scene]?.status==='succeeded');

  return <AppShell><div className="creative-workspace">
    <section className="mx-auto max-w-4xl"><div className="flex items-center gap-2 text-violet-300"><Sparkles size={18}/><span>AI Creative OS</span></div><h1 className="mt-3 text-4xl font-black md:text-5xl">{t('briefTitle')}</h1><p className="mt-3 text-zinc-500">{t('briefSubtitle')}</p><div className="card mt-7 p-3"><textarea className="min-h-36 w-full resize-none bg-transparent p-4 text-lg outline-none" value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder={t('promptPlaceholder')}/><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><label className="text-xs font-bold uppercase tracking-wider text-zinc-500">{t('qualityLabel')}</label><div className="mt-2 flex gap-2">{(['fast','quality','ultra'] as const).map(q=><button key={q} type="button" onClick={()=>setQuality(q)} className={`rounded-xl border px-3 py-2 text-sm ${quality===q?'border-violet-500 bg-violet-500/15 text-violet-200':'border-zinc-800 text-zinc-400'}`}>{q==='fast'?t('qualityFast'):q==='ultra'?t('qualityUltra'):t('qualityQuality')}</button>)}</div><div className="mt-2 text-xs text-zinc-600">{t('qualityHint')}</div></div><button onClick={run} disabled={busy||!prompt.trim()} className="btn btn-primary">{busy?t('analyzing'):t('runBrief')}</button></div></div>{error&&<div className="mt-4 rounded-xl border border-red-900/50 bg-red-950/30 p-3 text-red-300">{error}</div>}</section>

    {brief&&<section className="mt-10 grid gap-5 lg:grid-cols-3"><div className="card p-6 lg:col-span-2"><div className="grid gap-5 md:grid-cols-2"><Field title={t('objective')} value={brief.objective}/><Field title={t('audience')} value={brief.audience}/><Field title={t('angle')} value={brief.angle}/><Field title={t('offer')} value={brief.offer}/></div><div className="mt-7"><h2 className="text-xl font-bold">{t('hooks')}</h2><div className="mt-3 space-y-2">{brief.hooks.map((x,i)=><div key={i} className="rounded-xl border border-zinc-800 bg-zinc-950/60 p-4">{i+1}. {x}</div>)}</div></div><div className="mt-7"><h2 className="text-xl font-bold">{t('concepts')}</h2><div className="mt-3 grid gap-3 md:grid-cols-3">{brief.concepts.map((x,i)=><div key={i} className="rounded-xl border border-zinc-800 bg-zinc-950/60 p-4"><div className="font-bold text-violet-300">{x.title}</div><div className="mt-2 text-sm leading-6 text-zinc-400">{x.idea}</div></div>)}</div></div></div><aside className="card p-6"><h2 className="text-xl font-bold">{t('script')}</h2><pre className="mt-4 whitespace-pre-wrap font-sans text-sm leading-7 text-zinc-300">{brief.script}</pre><div className="mt-6 rounded-xl border border-violet-500/20 bg-violet-500/10 p-4 text-sm text-violet-200">{t('nextStage')}</div><button onClick={generateVariants} disabled={variantBusy} className="btn btn-primary mt-4 w-full">{variantBusy?t('generatingVariants'):t('generateVariants')}</button>{saved&&<div className="mt-4 text-xs leading-5 text-emerald-300">{t('resultSaved')}</div>}{brief.mode==='development'&&<div className="mt-3 text-xs leading-5 text-amber-300">{t('demoMode')}</div>}</aside></section>}

    {brief&&<section className="mt-6"><div className="card p-6"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><h2 className="text-2xl font-black">{t('variantsTitle')}</h2><p className="mt-2 text-sm text-zinc-500">{t('variantsSubtitle')}</p></div><button onClick={generateVariants} disabled={variantBusy} className="btn btn-ghost">{variantBusy?t('generatingVariants'):variants.length?t('regenerateVariants'):t('generateVariants')}</button></div>{variants.length>0&&<div className="mt-5 grid gap-4 lg:grid-cols-3">{variants.map(v=><button key={v.variantKey} type="button" onClick={()=>setSelectedVariant(v)} className={`rounded-2xl border p-5 text-start transition ${selectedVariant?.variantKey===v.variantKey?'border-violet-500 bg-violet-500/10':'border-zinc-800 bg-zinc-950/50 hover:border-zinc-700'}`}><div className="flex items-center justify-between gap-3"><span className="rounded-lg bg-violet-500/15 px-2.5 py-1 text-sm font-black text-violet-300">{v.variantKey}</span>{selectedVariant?.variantKey===v.variantKey&&<CheckCircle2 size={17} className="text-emerald-300"/>}</div><div className="mt-4 text-lg font-bold">{v.title}</div><div className="mt-2 text-sm leading-6 text-zinc-400">{v.angle}</div><div className="mt-4 rounded-xl border border-zinc-800 bg-black/30 p-3 text-sm font-semibold">{v.hook}</div><div className="mt-4 text-xs font-bold uppercase tracking-wider text-zinc-600">{t('headline')}</div><div className="mt-1 text-sm">{v.headline}</div><div className="mt-4 text-xs leading-5 text-zinc-500">{v.rationale}</div></button>)}</div>}{variants.length>0&&<div className="mt-5 flex flex-col gap-3 rounded-2xl border border-violet-500/20 bg-violet-500/5 p-4 md:flex-row md:items-center md:justify-between"><div><div className="font-bold text-violet-200">{t('selectedVariant')}: {selectedVariant?.variantKey} — {selectedVariant?.title}</div><div className="mt-1 text-sm text-zinc-500">{t('variantStoryboardHint')}</div></div><button onClick={makeStoryboard} disabled={storyBusy||!selectedVariant} className="btn btn-primary">{storyBusy?t('generatingStoryboard'):t('buildSelectedVariant')}</button></div>}</div></section>}

    {storyboard&&<section className="mt-8"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-2xl font-black">{t('storyboardTitle')}</h2><p className="mt-2 text-sm text-zinc-500">{t('visualStageHint')}</p></div><div className="flex flex-wrap gap-2"><button onClick={generateAll} disabled={allBusy} className="btn btn-ghost inline-flex items-center gap-2"><WandSparkles size={17}/>{allBusy?t('generatingAllVisuals'):t('generateAllVisuals')}</button><button onClick={produceAll} disabled={productionBusy} className="btn btn-primary inline-flex items-center gap-2"><Film size={17}/>{productionBusy?t('producingAll'):t('produceAll')}</button></div></div>
      <div className="mt-4 grid gap-4 md:grid-cols-2">{storyboard.map((sc)=><article key={sc.scene} className="card overflow-hidden"><div className="p-5"><div className="flex items-center justify-between gap-3"><div className="font-bold text-violet-300">{t('scene')} {sc.scene}</div><div className="text-xs text-zinc-500">{sc.durationSeconds}{t('seconds')}</div></div><div className="mt-3 font-semibold">{sc.shot}</div><div className="mt-4 text-xs font-bold uppercase tracking-wide text-zinc-500">{t('visualPrompt')}</div><div className="mt-2 text-sm leading-6 text-zinc-300">{sc.visualPrompt}</div><div className="mt-4 text-xs font-bold uppercase tracking-wide text-zinc-500">{t('voiceover')}</div><div className="mt-2 text-sm leading-6 text-zinc-300">{sc.voiceover}</div>{sc.onScreenText&&<div className="mt-4 rounded-lg bg-zinc-950/70 p-3 text-sm">{sc.onScreenText}</div>}
        <div className="mt-4 grid grid-cols-1 gap-2 sm:grid-cols-3"><button onClick={()=>generateScene(sc)} disabled={sceneBusy[sc.scene]} className="btn btn-ghost inline-flex items-center justify-center gap-2"><ImageIcon size={16}/>{sceneBusy[sc.scene]?t('generatingVisual'):assets[sc.scene]?t('regenerateVisual'):t('generateVisual')}</button><button onClick={()=>generateVoice(sc)} disabled={voiceBusy[sc.scene]} className="btn btn-ghost inline-flex items-center justify-center gap-2"><Mic2 size={16}/>{voiceBusy[sc.scene]?t('generatingVoice'):voices[sc.scene]?t('regenerateVoice'):t('generateVoice')}</button><button onClick={()=>generateVideo(sc)} disabled={videoBusy[sc.scene]||!assets[sc.scene]} className="btn btn-ghost inline-flex items-center justify-center gap-2"><Video size={16}/>{videoBusy[sc.scene]?t('generatingVideo'):videos[sc.scene]?t('regenerateVideo'):t('generateVideo')}</button></div>
        {voices[sc.scene]&&<div className="mt-3 rounded-xl border border-zinc-800 bg-zinc-950/60 p-3"><div className="mb-2 flex items-center justify-between text-xs"><span className="text-zinc-400">{t('voiceReady')}</span><span className={voices[sc.scene].mode==='provider'?'text-emerald-300':'text-amber-300'}>{voices[sc.scene].mode==='provider'?t('providerMode'):t('developmentMode')}</span></div><audio controls src={voices[sc.scene].audioUrl} className="w-full"/></div>}
      </div>{assets[sc.scene]&&<div className="border-t border-zinc-800 bg-black"><div className="relative overflow-hidden"><img src={assets[sc.scene].imageUrl} alt={`${t('scene')} ${sc.scene}`} className={`aspect-[2/3] w-full object-cover ${videos[sc.scene]?.mode==='development'?'motion-preview':''}`}/>{videos[sc.scene]?.status==='processing'&&<div className="absolute inset-0 flex items-center justify-center bg-black/55"><div className="flex items-center gap-2 rounded-full bg-black/70 px-4 py-2 text-sm"><Loader2 className="animate-spin" size={16}/>{t('videoProcessing')}</div></div>}</div><div className="flex items-center justify-between gap-3 p-3 text-xs"><span className={assets[sc.scene].mode==='provider'?'text-emerald-300':'text-amber-300'}>{assets[sc.scene].mode==='provider'?t('providerVisual'):t('developmentVisual')}</span>{videos[sc.scene]?.status==='succeeded'&&<span className="inline-flex items-center gap-1 text-emerald-300"><CheckCircle2 size={14}/>{t('videoReady')}</span>}</div>{videos[sc.scene]?.videoUrl&&<video controls playsInline src={videos[sc.scene].videoUrl} className="aspect-[9/16] w-full bg-black object-cover"/>}</div>}</article>)}</div>
      <div className="card mt-6 flex flex-col items-start justify-between gap-4 p-5 md:flex-row md:items-center"><div><div className="font-bold">{t('productionReadyTitle')}</div><div className="mt-1 text-sm text-zinc-500">{allProductionReady?t('productionReadyBody'):t('productionPendingBody')}</div></div><button onClick={assemble} className="btn btn-primary inline-flex items-center gap-2" disabled={!allProductionReady||assemblyBusy}><Film size={17}/>{assemblyBusy?t('assemblingVideo'):t('buildVideo')}</button></div>
      {finalAsset&&finalAsset.status==='processing'&&<div className="card mt-5 p-5"><div className="flex items-center gap-2 text-violet-200"><Loader2 className="animate-spin" size={18}/><b>{t('assemblingVideo')}</b></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-zinc-900"><div className="h-full bg-violet-500 transition-all" style={{width:`${Math.max(4,finalAsset.progress??4)}%`}}/></div></div>}
      {finalAsset&&finalAsset.status!=='processing'&&<div className="card mt-5 p-5"><div className="flex items-center gap-2 text-emerald-300"><CheckCircle2 size={18}/><b>{t('finalReady')}</b></div>{finalAsset.videoUrl?<video controls playsInline src={finalAsset.videoUrl} className="mt-4 max-h-[720px] w-full rounded-2xl bg-black"/>:<div className="mt-4 rounded-xl border border-amber-500/20 bg-amber-500/10 p-4 text-sm text-amber-200">{t('manifestReady')} {finalAsset.manifestUrl&&<a className="underline" href={finalAsset.manifestUrl} target="_blank">{t('openManifest')}</a>}</div>}</div>}
    </section>}
  </div></AppShell>;
}
function Field({title,value}:{title:string;value:string}){return <div><div className="text-xs font-bold uppercase tracking-wider text-zinc-500">{title}</div><div className="mt-2 leading-7 text-zinc-200">{value}</div></div>}
