'use client';
import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { ArrowLeft, BrainCircuit, Plus, Trash2 } from 'lucide-react';
import { createClient } from '@/lib/supabase';
import { useLanguage } from '@/lib/i18n';
import { LanguageToggle } from '@/components/language-toggle';

const split=(v:string)=>v.split(/\n|,/).map(x=>x.trim()).filter(Boolean);
export default function BrandBrainPage(){
  const supabase=useMemo(()=>createClient(),[]); const router=useRouter(); const {t}=useLanguage();
  const [brand,setBrand]=useState<any>(null); const [products,setProducts]=useState<any[]>([]); const [offers,setOffers]=useState<any[]>([]); const [audiences,setAudiences]=useState<any[]>([]); const [guidelines,setGuidelines]=useState<any>(null); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [msg,setMsg]=useState('');
  const [product,setProduct]=useState({name:'',description:'',price:''}); const [offer,setOffer]=useState({name:'',original:'',sale:''}); const [audience,setAudience]=useState({name:'',description:'',pains:''});
  const [rules,setRules]=useState({preferred:'',forbidden:'',claims:'',cta:''});
  async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/auth');return;}const {data:activeOrg}=await supabase.rpc('get_active_organization');const m=activeOrg?{organization_id:String(activeOrg)}:null;if(!m){router.replace('/onboarding');return;}const {data:b}=await supabase.from('brands').select('*').eq('organization_id',m.organization_id).order('created_at',{ascending:true}).limit(1).single();if(!b){router.replace('/onboarding');return;}const [p,o,a,g]=await Promise.all([supabase.from('brand_products').select('*').eq('brand_id',b.id).order('created_at',{ascending:false}),supabase.from('brand_offers').select('*').eq('brand_id',b.id).order('created_at',{ascending:false}),supabase.from('brand_audiences').select('*').eq('brand_id',b.id).order('created_at',{ascending:false}),supabase.from('brand_guidelines').select('*').eq('brand_id',b.id).maybeSingle()]);setBrand(b);setProducts(p.data??[]);setOffers(o.data??[]);setAudiences(a.data??[]);setGuidelines(g.data??null);const x=g.data;setRules({preferred:(x?.preferred_phrases??[]).join('\n'),forbidden:(x?.forbidden_phrases??[]).join('\n'),claims:(x?.forbidden_claims??[]).join('\n'),cta:String(x?.cta_preferences?.default??'')});setLoading(false)}
  useEffect(()=>{load()},[]);
  async function addProduct(){if(!brand||!product.name.trim())return;setBusy(true);const {error}=await supabase.from('brand_products').insert({brand_id:brand.id,name:product.name.trim(),description:product.description.trim()||null,price:product.price?{amount:Number(product.price),currency:'EGP'}:null});setBusy(false);if(error){setMsg(error.message);return;}setProduct({name:'',description:'',price:''});await load()}
  async function addOffer(){if(!brand||!offer.name.trim())return;setBusy(true);const {error}=await supabase.from('brand_offers').insert({brand_id:brand.id,name:offer.name.trim(),original_price:offer.original?Number(offer.original):null,offer_price:offer.sale?Number(offer.sale):null,currency:'EGP',active:true});setBusy(false);if(error){setMsg(error.message);return;}setOffer({name:'',original:'',sale:''});await load()}
  async function addAudience(){if(!brand||!audience.name.trim())return;setBusy(true);const {error}=await supabase.from('brand_audiences').insert({brand_id:brand.id,name:audience.name.trim(),description:audience.description.trim()||null,pains:split(audience.pains)});setBusy(false);if(error){setMsg(error.message);return;}setAudience({name:'',description:'',pains:''});await load()}
  async function saveRules(){if(!brand)return;setBusy(true);const payload={brand_id:brand.id,preferred_phrases:split(rules.preferred),forbidden_phrases:split(rules.forbidden),forbidden_claims:split(rules.claims),cta_preferences:{default:rules.cta.trim()},content_rules:{}};const {error}=await supabase.from('brand_guidelines').upsert(payload,{onConflict:'brand_id'});setBusy(false);setMsg(error?error.message:t('brandBrainSaved'));if(!error)await load()}
  async function remove(table:string,id:string){setBusy(true);await supabase.from(table).delete().eq('id',id);setBusy(false);await load()}
  if(loading)return <main className="p-10 text-center text-zinc-500">{t('loading')}</main>;
  return <main className="min-h-screen px-5 py-7"><div className="mx-auto max-w-6xl"><header className="flex items-center justify-between"><Link href="/dashboard" className="btn btn-ghost inline-flex items-center gap-2"><ArrowLeft size={16}/>{t('backDashboard')}</Link><LanguageToggle/></header><section className="mt-12"><div className="flex items-center gap-2 text-violet-300"><BrainCircuit size={20}/>{t('brandBrain')}</div><h1 className="mt-2 text-4xl font-black">{brand?.name}</h1><p className="mt-3 max-w-3xl text-zinc-500">{t('brandBrainSubtitle')}</p></section>{msg&&<div className="mt-5 rounded-xl border border-zinc-800 p-3 text-sm text-zinc-300">{msg}</div>}
  <section className="mt-8 grid gap-5 lg:grid-cols-3"><Panel title={t('products')}><input className="field" placeholder={t('productName')} value={product.name} onChange={e=>setProduct({...product,name:e.target.value})}/><textarea className="field min-h-24" placeholder={t('description')} value={product.description} onChange={e=>setProduct({...product,description:e.target.value})}/><input className="field" inputMode="decimal" placeholder={t('priceEgp')} value={product.price} onChange={e=>setProduct({...product,price:e.target.value})}/><button className="btn btn-primary w-full" disabled={busy||!product.name.trim()} onClick={addProduct}><Plus size={16}/>{t('addProduct')}</button><Items rows={products} label={(x:any)=>`${x.name}${x.price?.amount?` — ${x.price.amount} EGP`:''}`} onDelete={id=>remove('brand_products',id)}/></Panel>
  <Panel title={t('offers')}><input className="field" placeholder={t('offerName')} value={offer.name} onChange={e=>setOffer({...offer,name:e.target.value})}/><div className="grid grid-cols-2 gap-2"><input className="field" inputMode="decimal" placeholder={t('originalPrice')} value={offer.original} onChange={e=>setOffer({...offer,original:e.target.value})}/><input className="field" inputMode="decimal" placeholder={t('offerPrice')} value={offer.sale} onChange={e=>setOffer({...offer,sale:e.target.value})}/></div><button className="btn btn-primary w-full" disabled={busy||!offer.name.trim()} onClick={addOffer}><Plus size={16}/>{t('addOffer')}</button><Items rows={offers} label={(x:any)=>`${x.name}${x.offer_price?` — ${x.offer_price} ${x.currency}`:''}`} onDelete={id=>remove('brand_offers',id)}/></Panel>
  <Panel title={t('audiences')}><input className="field" placeholder={t('audienceName')} value={audience.name} onChange={e=>setAudience({...audience,name:e.target.value})}/><textarea className="field min-h-20" placeholder={t('audienceDescription')} value={audience.description} onChange={e=>setAudience({...audience,description:e.target.value})}/><textarea className="field min-h-20" placeholder={t('painPoints')} value={audience.pains} onChange={e=>setAudience({...audience,pains:e.target.value})}/><button className="btn btn-primary w-full" disabled={busy||!audience.name.trim()} onClick={addAudience}><Plus size={16}/>{t('addAudience')}</button><Items rows={audiences} label={(x:any)=>x.name} onDelete={id=>remove('brand_audiences',id)}/></Panel></section>
  <section className="card mt-5 p-6"><h2 className="text-xl font-black">{t('brandRules')}</h2><p className="mt-2 text-sm text-zinc-500">{t('brandRulesHint')}</p><div className="mt-5 grid gap-4 md:grid-cols-2"><TextArea label={t('preferredPhrases')} value={rules.preferred} onChange={v=>setRules({...rules,preferred:v})}/><TextArea label={t('forbiddenPhrases')} value={rules.forbidden} onChange={v=>setRules({...rules,forbidden:v})}/><TextArea label={t('forbiddenClaims')} value={rules.claims} onChange={v=>setRules({...rules,claims:v})}/><div><label className="text-sm font-bold">{t('defaultCta')}</label><input className="field mt-2" value={rules.cta} onChange={e=>setRules({...rules,cta:e.target.value})}/></div></div><button className="btn btn-primary mt-5" disabled={busy} onClick={saveRules}>{t('saveBrandRules')}</button></section>
  </div></main>;
}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <div className="card p-5"><h2 className="text-xl font-black">{title}</h2><div className="mt-4 space-y-3">{children}</div></div>}
function Items({rows,label,onDelete}:{rows:any[];label:(x:any)=>string;onDelete:(id:string)=>void}){return <div className="space-y-2 pt-2">{rows.map(x=><div key={x.id} className="flex items-center justify-between gap-3 rounded-xl border border-zinc-800 bg-black/20 p-3 text-sm"><span>{label(x)}</span><button onClick={()=>onDelete(x.id)} className="text-zinc-600 hover:text-red-300"><Trash2 size={15}/></button></div>)}</div>}
function TextArea({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <div><label className="text-sm font-bold">{label}</label><textarea className="field mt-2 min-h-28" value={value} onChange={e=>onChange(e.target.value)}/></div>}
